### ISSUE TITLE
Reference identifier patterns across multiple datasets

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#1]
http://xml2rfc.tools.ietf.org

IETF RFC
* `http://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.NNNN.xml`

IETF Internet-Draft
* `http://xml2rfc.ietf.org/public/rfc/bibxml-ids/reference.I-D.example-name.xml`
* `http://xml2rfc.ietf.org/public/rfc/bibxml-ids/reference.I-D.draft-example-name-99.xml`
* (Note: Leave draft- off when referencing a generic draft name, and add draft- when referencing a specific version of an internet-draft.)

IETF RFC Subseries
* `http://xml2rfc.ietf.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0099.xml`
* `http://xml2rfc.ietf.org/public/rfc/bibxml-rfcsubseries/reference.FYI.0099.xml`
* `http://xml2rfc.ietf.org/public/rfc/bibxml-rfcsubseries/reference.STD.0099.xml`

W3C
* `http://xml2rfc.ietf.org/public/rfc/bibxml4/reference.W3C.REC-example-name-date.xml`

3GPP
* `http://xml2rfc.ietf.org/public/rfc/bibxml5/reference.SDO-3GPP.1234.xml`
* `http://xml2rfc.ietf.org/public/rfc/bibxml-3gpp/reference.SDO-3GPP.1234.xml`

IEEE
* `http://xml2rfc.ietf.org/public/rfc/bibxml6/reference.IEEE.12345_date.xml`
* `http://xml2rfc.ietf.org/public/rfc/bibxml-ieee/reference.IEEE.12345_date.xml`

**Comment by strogonoff** [comment]
Since this applies to legacy datasets, it is superseded by https://github.com/ietf-ribose/bibxml-service/issues/11.

Current legacy path pattern matching implementation allows to either specify a legacy dataset specific prefix, or a function that converts legacy pattern following `reference.` to canonical reference (currently string matching BibXML data filename, used as primary key in our index), or (coming soon, and won’t work for external datasets) a function that builds arbitrary citation lookup query from the above legacy pattern.
