### ISSUE TITLE
GUI download links for BibXML, JSON and potential other serialization formats in future

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#113]
Maybe there should be a link somewhere on the page?

**Comment by strogonoff** [comment]
@ronaldtse This is by design, see https://github.com/ietf-ribose/bibxml-service/issues/62#issuecomment-1030058814. These links will not work for users, because those links point to API endpoints, which require Datatracker tokens.

**Comment by rjsparks** [comment]
@ronaldtse, @strogonoff 
This is not a good outcome - please reopen this ticket.

The comment on #62 is almost inscrutable - I think you're referring to the links to the formatted documents themselves? That's fine, but it has nothing to do with this comment.

The webservice can have its own access to the API and should make bibxml available to people, through the legacy URLs if nothing else.

A bibxml UI that doesn't make bibxml available is really puzzling.

**Comment by strogonoff** [comment]
Could someone outline where XML links fit in author’s workflow? That’d help bring them back with correct design/placement.

From what I was told earlier, XML was going to be accessed by authors only indirectly, via CLI tools that talk to BibXML service via API. I’ve added XML/JSON links as a sort of debugging measure, but now that they’re gone there seems to be an actual use case for them.

**Comment by rjsparks** [comment]
Some authors will assemble references, particularly to very old or to external SDO things, manually.

**Comment by strogonoff** [comment]
Understood, then I assume they would download the file, hand-edit and pass the result to the next tool (CLI or otherwise). 

I suspect the service could help authors make quick routine adjustments of this nature via GUI prior to download (and the service could also make use of the edits, e.g. suggest other authors, augment data source, etc.), though this would need more research than time currently allows…

**Comment by ronaldtse** [comment]
I actually failed to realise the issue that @strogonoff pointed out in https://github.com/ietf-ribose/bibxml-service/issues/113#issuecomment-1031858970 -- if in the future, usage of the Datatracker token is required (for tracking usage purposes at least), then the public BibXML links as we have today may not make sense.

I believe the correct outcome for now is to:
* make those links available on the GUI (for the public without a datatracker token but just want to manually retrieve and assemble)
* make legacy links available on the GUI (for the public who uses legacy paths)
* do not mandate a token for the API (the token is already optional)

@rjsparks is this accurate?

**Comment by strogonoff** [comment]
@ronaldtse note that if those links work in GUI without auth, then they will de fact become auth-less API.

However, if Datatracker OIDC integration works out of the box, then it is very little effort to add different but equivalently-behaving links that rely on OAuth2.

**Comment by rjsparks** [comment]
I think Anton is on the right track

**Comment by strogonoff** [comment]
XML & JSON download links are now shown to users who are authenticated via Datatracker.

They still use API endpoints. This was done by extending API authentication to recognize OAuth access token in session (however, if access token turns out to be expired, downloaded file will contain an error message—this can be fixed as #118 eventually).
