### ISSUE TITLE
Legacy path BibXML for RFC subseries `<referencegroup>` has different anchors

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#141]
The legacy path BibXML contains an anchor of pattern `BCPnn` and has internal anchors for the `<reference>` element.

https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0048.xml
```xml
<referencegroup anchor="BCP48" target="https://www.rfc-editor.org/info/bcp48">
<reference anchor="RFC3150" target="https://www.rfc-editor.org/info/rfc3150">
...
```

https://dev.bibxml.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0048.xml
```xml
<referencegroup anchor="BCP.0048">
<reference target="https://raw.githubusercontent.com/relaton/relaton-data-ietf/master/data/reference.RFC.3150.xml">
...
```

**Comment by strogonoff** [comment]
@ronaldtse:

1. It had been pointed out that root element’s anchor must _exactly_ match the filename provided without the `reference.` prefix, and most other cases are errors in the original xml2rfc data per [this comment](https://github.com/ietf-ribose/bibxml-service/issues/57#issuecomment-1023539266):

   > If there are specific mismatches in the current database between the returned anchors and the URL filenames, those are bugs, EXCEPT in the case where the anchor string contains characters such as "/".

3. Keeping above requirement in mind, the current implementation is such that if root element is a `<referencegroup>` then there is no anchor on the inner `<reference>` elements (because there is no unique filename for each). However, since the spec [states](https://datatracker.ietf.org/doc/html/rfc7991#section-2.40.1) that anchor on a `<reference>` is mandatory.

Right now I can triage (2) as a bug, but (1) conforms to IETF’s requirements and no change is required.
