### ISSUE TITLE
Implement mapping for W3C for misc dataset in service

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#144]

**Comment by strogonoff** [comment]
Question on xml2rfc path resolution.

We have these paths old xml2rfc paths in w3c dataset:

- reference.W3C.CR-2dcontext-20121217.xml
- reference.W3C.CR-2dcontext-20130806.xml
- reference.W3C.CR-2dcontext-20140821.xml
- reference.W3C.CR-2dcontext-20150702.xml

But we have only these docs in relaton-data-w3c:

- W3C SPSD-2dcontext-20210128
- W3C REC-2dcontext-20151119
- W3C NOTE-2dcontext2-20150929

So, xml2rfc paths don’t seem to have exact matches. Should BibXML service return roughly fitting fresh Relaton bibitem for those paths (but it would be different date and different type, e.g. REC instead of CR) or should it fall back to item in xml2rfc data archive if there’s no exact match?

**Comment by ronaldtse** [comment]
@strogonoff I just had this exact discussion with @rjsparks and @TonyLHansen yesterday.

* For the latest versions in bibxml4, we will map them to the latest versions.
* For the data that only existed in bibxml4, we keep them as fallback.

The reason why there are these non-current drafts is that bibxml4 has been accumulating content from the `td.rdf` file:
> From @rjsparks 
> that rdf is the source to my knowledge.
> I'm _guessing_ that what you're seeing is the result of accruing what had been at that rdf endpoint over time.
> Do we _need_ the older versioned drafts for w3c, or is reporting what tr.rdf says at any given point in time sufficient?

> From @TonyLHansen 
> The w3c URL has indeed already changed link locations at least a couple times. And the extra document references are most likely from not deleting older references not listed in the newer links.

**Comment by strogonoff** [comment]
@ronaldtse

> For the latest versions in bibxml4, we will map them to the latest versions.
> For the data that only existed in bibxml4, we keep them as fallback.

My above examples—are they considered “only existing on bibxml4” or are they considered mappable?

**Comment by strogonoff** [comment]
Mappings given in https://github.com/ietf-ribose/bibxml-service/issues/130 were added to bibxml-data-archive in https://github.com/ietf-ribose/bibxml-data-archive/commit/d2af3605efedc44b47da8e16d78121775b04b88b and https://github.com/ietf-ribose/bibxml-data-archive/commit/6a85aba52cad340a1147d8bbf9847c6f285b74e3.
