### ISSUE TITLE
rfc bibxml has a space in its download filename

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#150]
At https://dev.bibxml.org/get-one/by-docid/?docid=RFC+4214&doctype=IETF&query=4214, the download link contains a space in the filename. The last segment is `/RFC 4214.xml` - it should at least be  `/RFC4214.xml`, and I'm surprised it's not `/reference.RFC.4214.xml`

**Comment by strogonoff** [comment]
> I'm surprised it's not /reference.RFC.4214.xml

The `reference.` prefix is allowed in xml2rfc compatibility API, but otherwise it has no meaning and was considered unnecessary in the new API. It can be added, but I would like to clarify the purpose.

> the download link contains a space in the filename

Downloaded filename is currently generated using primary document identifier (if there is one, otherwise first available document identifier). The document in question has three identifiers: “RFC 4214” (primary), “RFC4214” and “10.17487/RFC4214”.

Should we use a different primary identifier? This would be an issue for https://github.com/ietf-ribose/relaton-data-rfcs. (cc @ronaldtse)

**Comment by TonyLHansen** [comment]
The downloadable link should never have a space in it. I would use RFC4214 without the space.

Not having the "reference." prefix MIGHT lead to future confusion if someone thought they were going to get the RFC itself instead of reference information for the RFC. Robert, what do you think?

**Comment by strogonoff** [comment]
Keep in mind that space is not part of the URL. It is part of a Content-Disposition header in HTTP response. It is indicative and is used only as default value in the “Save as…” dialog shown to the user. It seems to me that the only reason to explicitly forbid spaces would be OS-level limitation, but maybe I am missing something here…

**Comment by rjsparks** [comment]
> It can be added, but I would like to clarify the purpose.
People are used to the `reference.` handle - it is what they will type in their source code even if they used the UI to download the bibxml rather than the legacy URI mechanism. On disk, it organizes the reference files away from source files in unadorned directory listings.

Especially given Tony's comment, I think this is the right thing to do.

**Comment by rjsparks** [comment]
> Should we use a different primary identifier?
> It seems to me that the only reason to explicitly avoid/replace spaces would be OS-level limitation, but maybe I am missing something…

Yes - use "RFCxxxx". This has been a long discussion that has come up in many places over the years, `RFC nnnn` is something that we use in prose. `RFCnnnn` is what we use for handles software needs to manipulate, including filenames.

For example, the _canonical_ way (at the moment) to access  RFCs is at https://www.rfc-editor.org/rfc/. Note the lack of spaces in the filenames.

**Comment by ronaldtse** [comment]
Thanks @TonyLHansen and @rjsparks for the clarification.

I do share the sentiment from @strogonoff that the `reference.` prefix seems superfluous, but understand that it can be useful for legacy compatibility and for common understanding. 

If I may regurgitate the main point of @TonyLHansen and @rjsparks is that users "expect" the downloaded BibXML file to have a filename of `reference.RFCnnnn.xml`, and that breaking this assumption may cause issues with existing users.

@strogonoff could you please help with:
1. Use `reference.RFCnnnn.xml` as the filename offered for download
2. Remove the space in the API query, instead of `RFC nnnn` use `RFCnnnn` to prevent confusion

(@strogonoff let us discuss what is considered the "primary" identifier internally)

**Comment by strogonoff** [comment]
> users "expect" the downloaded BibXML file to have a filename of reference.RFCnnnn.xml, and that breaking this assumption may cause issues with existing users.

Understood, this will be accommodated.

As a side note, it’d be helpful to know exact use scenarios, which are still vague. Such as “in order to achieve X, the user expects to be able to go to Y, search for Z, download file, etc.”

This might have value extending beyond the immediate RFP scope that’s being handed off.

**Comment by ronaldtse** [comment]
Thanks @strogonoff , agree that documenting usage scenarios remain useful.

**Comment by strogonoff** [comment]
Next version uses the following logic:

- Take either given `anchor` GET parameter or `docid` with scope=anchor (if any) as anchor
- Return `reference.<anchor>.<serialization format>` as filename in the Content-Disposition header, so that it’s suggested to the user as default filename

**Comment by TonyLHansen** [comment]
Both the current bibxml-doi and bibxml-iana support "?anchor=EXAMPLE" to override the anchor value that is returned.

This should eventually be extended to all of the bibxml-xyz.

See the web page [https://xml2rfc.tools.ietf.org/](https://xml2rfc.tools.ietf.org/) for more info.
