### ISSUE TITLE
rfc bibxml has bad anchors

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#151]
What https://dev.bibxml.org/get-one/by-docid/?docid=RFC+4214&doctype=IETF&query=4214 offers for download starts out
```
<reference target="https://www.rfc-editor.org/info/rfc4214" anchor="RFC 4214">
```
That should be `anchor="RFC4214"`. No space please.

Further, what's served at https://dev.bibxml.org/public/rfc/bibxml-rfcs/reference.RFC.4214.xml starts out
```
<reference target="https://www.rfc-editor.org/info/rfc4214" anchor="RFC.4214">
```
There should not be a period in that anchor.

**Comment by strogonoff** [comment]
Regarding https://dev.bibxml.org/public/rfc/bibxml-rfcs/reference.RFC.4214.xml, I was going off https://github.com/ietf-ribose/bibxml-service/issues/57#issuecomment-1023539266, from which I got the impression that anchor should exactly match filename.

**Comment by strogonoff** [comment]
Regarding https://dev.bibxml.org/get-one/by-docid/?docid=RFC+4214&doctype=IETF&query=4214, after today’s change it should prefer identifier with scope=anchor. (Which value that will be is down to data sources, but for RFCs that value is RFCXXXX without spaces.)

**Comment by rjsparks** [comment]
This takes us into legacy RFCXML. These anchors are _used_ in RFCXML source, and the formats are specific to the individual domains. It is unfortunate that they didn't grow more consistency when they developed over time, but they are what they are, and trying to make them consistent right now is simply not an option.

**Comment by ronaldtse** [comment]
In this case then for legacy paths we can implement the patterns as described in https://github.com/ietf-ribose/bibxml-service/issues/151#issuecomment-1064218979 .

How about returns from the new API?
* Do we want to hard-code the anchors to the same names; or
* add the "anchor" in the URL as a parameter value so that the user (i.e. xml2rfc) could potentially customise in the future?

**Comment by rjsparks** [comment]
The user being affected is not xml2rfc, it is the draft author.

Authors refer to the anchors when making references from within their prose to a reference.
The string they use for `target=` is what we're talking about.

If the new API returns a different anchor, an author would have to update all of the places the reference was used, changing the target string before the document could be processed.

In particular, any software that tried to bridge the gap _for_ the author would now have a much harder job than "Retrieve the same bibxml using a different technique".

The requirement for this project was to reproduce the existing Bibxml. (Acknowledging that we've adjusted where the existing bibxml is clearly broken).

The new API should return the same anchors.

**Comment by ronaldtse** [comment]
Thank you @rjsparks for the clarification. 

@strogonoff can you please help fix the anchors as described for the datasets mentioned above, i.e.:
* RFC: https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.0001.xml => anchor of "RFC0001" (omission of period)
* RFC subseries: https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0004.xml => anchor of "BCP4" (omission of period and leading zeros)
* bibxml8/IANA. https://xml2rfc.tools.ietf.org/public/rfc/bibxml8/reference.IANA.dns-parameters.xml => anchor of "DNS-PARAMETERS" (upper case of filename)

**Comment by strogonoff** [comment]
@ronaldtse 

1) I want to confirm the change of requirements. It was stated to me on a couple of occasions that xml2rfc anchor should match requested filename. That’s how it works now: via xml2rfc API, one can request https://dev.bibxml.org/public/rfc/bibxml/reference.RFC.0001.xml and see anchor `RFC.0001`, or one can request https://dev.bibxml.org/public/rfc/bibxml/reference.RFC0001.xml and see anchor `RFC0001`. (And via new API, one can supply any anchor, while Relaton’s `scope=anchor` docid is used by default.)

2) If we have fixed anchors Ideally we should provide the requisite anchor value in Relaton’s bibliographic item YAML, and specify how BibXML can obtain the value. Otherwise we’ll be stuck with brittle string manipulation and lots of special cases. For example, if `relaton-data` repositories update YAML so that `docid` contains a structure with `scope=anchor` and anchor conforming to formats you listed in your previous comment, then it will just work in new API with no changes to BibXML service (and if (1) is confirmed, xml2rfc API can also ignore the filename and use these anchors).

**Comment by ronaldtse** [comment]
@strogonoff the anchors have been updated for RFCs, RFC subseries and IANA. Can you help check the status of this task? Thanks.
