### ISSUE TITLE
Implement legacy path pattern: W3C (`bibxml4`)

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#16]
W3C (bibxml4)
* (previous location) http://xml2rfc.tools.ietf.org/public/rfc/bibxml4/
* Pattern 1: http://xml2rfc.ietf.org/public/rfc/bibxml4/reference.W3C.REC-example-name-date.xml

Legacy pattern(s) to implement:
* https://{hostname}/public/rfc/bibxml4/reference.W3C.REC-{example-name}-{date}.xml

We need to parse the pattern to return the appropriate BibXML content.

**Comment by strogonoff** [comment]
Path pattern that works right now: http://34.229.41.119:8000/public/rfc/bibxml4/reference.WD-SWBP-SKOS-CORE-GUIDE-20051102.xml

**Comment by strogonoff** [comment]
Updated to: [/public/rfc/bibxml4/reference.W3C.WD-SWBP-SKOS-CORE-GUIDE-20051102.xml](http://34.229.41.119:8000/public/rfc/bibxml4/reference.W3C.WD-SWBP-SKOS-CORE-GUIDE-20051102.xml)

**Comment by strogonoff** [comment]
@ronaldtse 

- The pattern in the description: `/public/rfc/bibxml4/reference.W3C.REC-example-name-date.xml`
- We have this working path: `/public/rfc/bibxml4/reference.W3C.WD-SWBP-SKOS-CORE-GUIDE-20051102.xml`

This works because files in `bibxml-data-w3c` seem to be already correctly named according to legacy path convention, e.g. “WD-SWBP-SKOS-CORE-GUIDE-20051102.xml”.

I’m closing, feel free to reopen if I got it wrong.

**Comment by ronaldtse** [comment]
Excellent. Thanks @strogonoff !
