### ISSUE TITLE
Implement legacy path pattern: IANA references (`bibxml8`)

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#19]
IANA references (bibxml8)
* (In the old implementation this is a dynamic fetch service, in our implementation we treat this as a dataset)
* Pattern 1: https://xml2rfc.tools.ietf.org/public/rfc/bibxml8/reference.IANA.sip-parameters.xml
* Pattern 2: https://xml2rfc.tools.ietf.org/public/rfc/bibxml-iana/reference.IANA.sip-parameters.xml

Legacy pattern(s) to implement:
* Pattern 1: http://xml2rfc.ietf.org/public/rfc/bibxml8/reference.IANA.{example-table-name}.xml
* Pattern 2: http://xml2rfc.ietf.org/public/rfc/bibxml8-iana/reference.IANA.{example-table-name}.xml

**Comment by strogonoff** [comment]
Path patterns were implemented. Compare http://xml2rfc.tools.ietf.org/public/rfc/bibxml8/reference.IANA.sip-parameters.xml with https://dev.bibxml.org/public/rfc/bibxml8/reference.IANA.sip-parameters.xml.

The [path tester script](https://github.com/ietf-ribose/xml2rfc-mapping-convertor#test_pathspy) cannot help here, because there’s no reference list of paths under https://github.com/ietf-ribose/bibxml-data-archive/tree/main/bibxml8.
