### ISSUE TITLE
The UI is baffling

### ISSUE THREAD

**Issue by martinthomson** [ietf-ribose/bibxml-service#191]
I don't quite know how else to put this, but I found the entire service confusing.  The multiple search boxes took some real head-scratching to decipher.  The way the help is presented doesn't really make it easier to understand.

It would help if the service described what it attempts to achieve (this is a database of citations), the sort of information you might include, how entries are identified, and maybe then hide the advanced querying capabilities.  Documentation of those advanced querying capabilities probably needs to be accompanied by more prose than is provided, but that can be hidden.

The page that shows the details of a citation is oddly laid out.  There is a lot of space and some lines, but these don't line up in any obvious way (I think the colons line up) so the layout doesn't seem to cohere the disparate pieces information.  My first search landed on https://bibxml.ietf.org/get-bibliographic-item/?query=QUIC (which wasn't RFC 9000; a separate issue) so it took me a while to work out that the information here related to a single citation to the IANA registries for QUIC.

**Comment by strogonoff** [comment]
> The multiple search boxes took some real head-scratching to decipher. 

Thank you for pointing this out, I see that quick search help summary may not be enough and extra pointers or FAQ/help page could be warranted.

1. It’s assumed that one would typically search using the Quick Search box first, which attempts to locate an exactly matching document and redirect to it; if one is not found then it tries various search methods.
2. If one has a more specific query, one can search using document ID substring match, JSON substructure match or JSON path query—however, those require some knowledge of the underlying bibliographic data schema (field names and value types).
3. Then there’s the _web search_, which is listed last but is perhaps most useful in some cases, as it supports many typical operators like `+term`, `-term`, quotes for exact phrases and so on.

> My first search landed on https://bibxml.ietf.org/get-bibliographic-item/?query=QUIC (which wasn't RFC 9000; a separate issue)

The case of “QUIC” is interesting. The Quick Search widget behavior was indeed suboptimal here, there’s a number of documents one may have wanted to see for “quic” but unfortunately one of them was an exact hit.

I wish we encountered this case before, it may hint that current search behavior may not be best—I suspect we should use web search instead and avoid redirecting to exact matches even if they exist.

> The page that shows the details of a citation is oddly laid out.

As a core developer/designer, I’d say there is _significant_ space for improvement as far as presenting data and visual hierarchy goes, for a few reasons:

* GUI was not considered the primary use scenario at this time. The primary use case for the GUI was limited to, more or less, “one wants to search for a document, ensure that the correct document is found, and download BibXML”. As a result, not that much effort was dedicated to GUI as a whole and to aspects like legacy browser support (if UA, for example, doesn’t support CSS grid, the outcome may be suboptimal).
* Generally, the more assumptions can be made about the data, the better the conditions for designing the most fitting layout for it. Unfortunately, in this case it turned out that the extent and shape of available data varies significantly depending on authoritative source (i.e., any number of fields can be missing), which posed challenges when it comes to reliable visual hierarchy in page layout.

The GUI was designed to list bibliographic item’s metadata/data fields and their values in a compact way without relying on particular fields being available in source data. Values are left-aligned and field labels are right-aligned, so that layout lines up the starts of values; value containers are scrollable in case of large values or multiple values—this seemed to result in a more or less balanced and “at-a-glance” readable layout of predictable overall dimensions. Admittedly, there is an element of subjectivity to it and it’s not ideal in some scenarios. Especially in case of sparse source data, it may be a bit confusing as to what is lining up with what.

Thank you for the comments, there are important points that could be used in further design iterations.

**Comment by strogonoff** [comment]
Working on adding some brief overview and an expanded About page.

Landing page before & after:

<img width="1211" alt="Screenshot 2022-05-07 at 4 11 30 AM" src="https://user-images.githubusercontent.com/292959/167217515-562b97cc-0467-4507-8461-ea60eae457c9.png">

<img width="1211" alt="Screenshot 2022-05-07 at 4 11 33 AM" src="https://user-images.githubusercontent.com/292959/167217522-95afee1a-c988-41e8-a8dd-b255dc3c6eed.png">

**Comment by strogonoff** [comment]
Now deployed at dev.bibxml.org.

**Comment by strogonoff** [comment]
A more recent update should hopefully make bibliographic item GUI saner, feedback is welcome…

<img width="1078" alt="Screenshot 2022-06-13 at 1 37 39 AM" src="https://user-images.githubusercontent.com/292959/173282546-77d47e8a-6fb6-4ba8-a9f7-241113b0b66a.png">

**Comment by martinthomson** [comment]
From what I can see, that does look a lot better.  Busy, but that's unavoidable.
