### ISSUE TITLE
Make I-D xml2rfc `anchor` attribute formatting logic part of the service, don’t use `docid` for that anymore

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#206]

**Comment by ronaldtse** [comment]
For 2 and 3, I do not think we need to retain the old anchors. For legacy paths that depend on those anchors, we can already identify the anchor names from the legacy path itself and generate that anchor for those retrievals.

@rjsparks @kesara could this be confirmed? Thanks!

**Comment by ronaldtse** [comment]
(mistakenly closed...)

**Comment by rjsparks** [comment]
This means someone using the non-legacy paths to obtain bibxml will get a different document than someone using the legacy paths? That dos not seem right. Can you expand the question a little more for me?

**Comment by strogonoff** [comment]
> This means someone using the non-legacy paths to obtain bibxml will get a different document than someone using the legacy paths? That dos not seem right. Can you expand the question a little more for me?

I believe the only difference would concern `anchor` values:

1. If XML is requested via xml2rfc-style API, we would derive those values from requested xml2rfc filename (using filename as anchor, possibly with some munging).
2. If XML is requested via regular API (non-xml2rfc path), the anchor would be derived from primary document identifier in that case.

Looking at xml2rfc spec, anchor is [expected](https://xml2rfc.tools.ietf.org/xml2rfc-doc.html#name-anchor-attribute-required-3) to be used for human-readable labeling and internal links within a document. If it’s not used for external linkage, I wonder whether changing the anchor _slightly_ would break anything…

**Comment by ronaldtse** [comment]
> This means someone using the non-legacy paths to obtain bibxml will get a different document than someone using the legacy paths? That dos not seem right. Can you expand the question a little more for me?

It's not exactly that, instead:
> someone using the non-legacy paths to obtain bibxml may get a different "anchor" than someone using the legacy paths

The following reasons explain why we think this is the correct move moving forward. 

Note: the current implementation already returns correct anchors for legacy paths. This topic is about how to retain identical behavior by cutting down code and stored data requirements.

1. Users who use legacy paths will see an anchor identical to that of today. There is no change to this behavior.
2. People who use the new API will obtain an anchor of their choice, as previously agreed, because the URL will include specification on what the anchor is.

Use case 1 is the legacy paths. We currently use the bibxml-data-archive repo to achieve this. As @strogonoff pointed out, some "anchors" are manually assigned -- they have nothing to do with the filename or the identifier of the underlying information resource.

The purpose of this issue is to migrate the "URL/filename" to "anchor" mapping to the mapping repository (in addition to the "URL/filename" mapping to the canonical document identifier).

> someone using the non-legacy paths to obtain bibxml may get a different "anchor" than someone using the legacy paths

Yes, and that is correct behavior. Users from use case 1 can get an anchor different from that of use case 2, depending on the chosen anchor of the user of use case 2.

Hope this clarifies!

**Comment by rjsparks** [comment]
This seems to be right.
