### ISSUE TITLE
Add external source for IANA documents, using their assignments API

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-service#227]
Currently, we resolve IANA references statically indexed via relaton-data-iana.

However, since IANA seems to offer an API endpoint, it can be registered as another external source, like Crossref and Datatracker. We could use it as a fallback in xml2rfc paths, and possibly in service GUI (if search is augmented to support external sources).

**Comment by ronaldtse** [comment]
@strogonoff instead of the API, we directly use the IANA rsync endpoint which contains the full data. The rsync endpoint is the authoritative data set and is preferable over the IANA website (not an API) which is generated from the data set.

**Comment by strogonoff** [comment]
> @strogonoff instead of the IANA website (it's not an API), we directly use the IANA rsync endpoint which contains the full data. The rsync endpoint is the authoritative data set and is preferable over the IANA website (not an API) which is generated from the data set.

It’s like with Datatracker though, using external source could provide more up-to-date bibliographic data before it’s indexed…🤔

**Comment by ronaldtse** [comment]
> It’s like with Datatracker though, using external source could provide more up-to-date bibliographic data before it’s indexed…🤔

The nature of I-Ds and IANA registries are different.

Authors have direct access to publish I-Ds, and therefore it is reasonable they want to cite a published draft directly.

Authors have NO access to creating or modifying IANA registries. IANA registries are managed by IANA, a non-IETF organization. Thus RFC/I-D authors cannot have an expectation that a new IANA registry is created at some certain time. Remember we are talking about registries, not registry items.

Moreover, the frequency of I-Ds is high, IANA registries is low.

Finally, the same argument can be applied to ALL non-datatracker bibliographic sources. IANA is a separate organization, just like NIST and IEEE.

We need to strike a balance between resources and effectiveness. At this point, I prefer the mode of operation today for IANA registries because it is predictable and complete in terms of data.
