### ISSUE TITLE
W3C references from authoritative endpoint do not contain contact/affiliation information

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#235]
Some of the hand-crafted W3C references in the `bibxml2` folder contain contact information, e.g.:
```xml
<?xml version="1.0" encoding='UTF-8'?>
<reference anchor="W3C.PICS-rules" target="http://www.w3.org/TR/REC-PICSRules">
  <front>
    <title>PICSRules 1.1</title>
    <author initials="C." surname="Evans" fullname="Christopher Evans">
      <organization abbrev="W3C">Microsoft</organization>
      <address>
        <email>cevans@microsoft.com</email>
      </address>
    </author>
    <author initials="C.D.W." surname="Feather" fullname="Clive D.W. Feather">
      <organization abbrev="W3C">Demon Internet Ltd.</organization>
      <address>
        <email>clive@demon.net</email>
      </address>
    </author>
    <author initials="A." surname="Hopmann" fullname="Alex Hopmann">
      <organization>Microsoft</organization>
      <address>
        <email>alexhop@microsoft.com</email>
      </address>
    </author>
    <author initials="M." surname="Presler-Marshall" fullname="Martin Presler-Marshall">
      <organization>IBM</organization>
      <address>
        <email>mpresler@us.ibm.com</email>
      </address>
    </author>
    <author initials="P." surname="Resnick" fullname="Paul Resnick">
      <organization>AT&amp;T</organization>
      <address>
        <email>presnick@research.att.com</email>
      </address>
    </author>
    <date day="29" month="December" year="1997"/>
  </front>
  <seriesInfo name="W3C Recommendation" value="REC-PICSRules"/>
</reference>
```

However, the authoritative W3C endpoint [`tr.rdf`](http://www.w3.org/2002/01/tr-automation/tr.rdf) does not provide any contact or affiliation information.

The corresponding data file is available here:
https://github.com/relaton/relaton-data-w3c/blob/main/data/rec-picsrules-971229.yaml

@rjsparks is it worth asking W3C about their API that provides this information?

**Comment by rjsparks** [comment]
cc @martinthomson

**Comment by fluffy** [comment]
@dontcallmedom - any chance you could help on this ?

**Comment by dontcallmedom** [comment]
specref doesn't include contact or affiliation information about editors (but :+1: to @martinthomson that this is what most W3C specs use nowadays to generate their own list of references). 

The affiliation information can be imperfectly retrieved via the [W3C API](https://w3c.github.io/w3c-api/)  (imperfectly because I think the best you can hope is retrieve the latest known affiliation of the editors of a spec, not necessarily the affiliation they had when they served as editor of the specification). Contact information is not something that is systematically provided in our specifications in general, and cannot be retrieved from the W3C API based on privacy concerns.

**Comment by ronaldtse** [comment]
Thanks @martinthomson @fluffy and @dontcallmedom for the advice!

Given the responses, both specref and the W3C API would not be able to provide contact of affiliation information for contributors. I'm happy to let this issue slide for now. 

@rjsparks please feel free to re-open if you feel otherwise.

PS. @dontcallmedom just saw you in the MSF call!
