### ISSUE TITLE
Issue with "DOI" and "RFC" seriesInfo entries reverse-ordered in some bib. items for RFCs

### ISSUE THREAD

**Issue by lbartholomew-rpc** [ietf-ribose/bibxml-service#239]
"DOI" and "RFC" seriesInfo entries are reverse-ordered in some bib. items for RFCs. 

Have seen this issue in one document so far -- reference entries for RFCs 3209, 3473, 4426, 6372, 7412, and 8776 -- so there are probably more.  For example, see

https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.3209.xml  (correct)
https://bib.ietf.org/public/rfc/bibxml/reference.RFC.3209.xml  (incorrect; ordering is swapped)

Please also see

https://www.rfc-editor.org/v3test/rfc9270-bib-bugs-15July2022.xml
https://www.rfc-editor.org/v3test/rfc9270-bib-bugs-15July2022.txt
https://www.rfc-editor.org/v3test/rfc9270-bib-bugs-15July2022-rfcdiff.html

**Comment by strogonoff** [comment]
The service provides no guarantee that XML formatting is maintained exactly the same, this means attribute ordering and other formatting aspects may differ from legacy XML (in addition to data values being different when newer data is available).

However, if there is a canonical order of seriesInfo items defined by the BibXML/RFCXML/xml2rfc spec, the XML serialized can comply with that…

**Comment by ronaldtse** [comment]
@lbartholomew-rpc if the RPC requires the order of bibliographic items to be a particular one, could you help specify the desired behavior? Thanks.

**Comment by lbartholomew-rpc** [comment]
Hi, Anton and Ronald.  I checked with a couple other RPC folks re. your notes.  Here is a template (from Jean Mahoney; thanks, Jean!  Then I added the editor and BCP/STD/FYI entries) of current RPC conventions.  The editor designation, BCP/STD/FYI designation, refcontent entry, and annotation entry would  be included where applicable.  The refcontent entry will be used for non-RFC references.  We've included the annotation entry for completeness, because sometimes authors add it when they edit a reference (for example, the "(In Russian)" entries in RFC 9227).

     <reference anchor="CITATION-TAG" target="URL">
        <front>
          <title>TITLE</title>
          <author initials="" surname="" fullname="" role="editor">
            <organization />
          </author>
          <date month="MONTH" year="YEAR"/>
        </front>
        <seriesInfo name="BCP/STD/FYI" value="NUMBER"/>
  	<seriesInfo name="NAME" value="VALUE"/>
        <seriesInfo name="DOI" value="VALUE"/>
        <refcontent>REFCONTENT</refcontent>
        <annotation>ANNOTATION</annotation>
      </reference>

Here are three RFC bibxml examples that give us the reference output style seen in XML-era published RFCs to date:

<https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml>  (example BCP RFC)
<https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.4949.xml>  (example FYI RFC)
<https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.5234.xml>  (example STD RFC with editor designation)

Thank you.

**Comment by strogonoff** [comment]
Just to clarify, the returned XML as it is now complies with the schema, is that correct? I’m trying to use this to assess the severity of the issue.

**Comment by rjsparks** [comment]
The XML produced does not violate the schema - this is a workflow enhancement for the RPC, which has to manually look at, and use text diff tools over the xml. Adhering to the _convention_ they have for ordering will simplify their tasks.

**Comment by rjsparks** [comment]
Note carefully the text-diff-tools use case - authors end up using this too. Whether we teach the emitter to follow the RPC conventions or not (I think we should), the output needs to be _stable_, even if reordering doesn't matter to the grammar.

**Comment by strogonoff** [comment]
- `seriesInfo` items were changing order since BibXML serializer used by this service stored series extractors in a `set()` when applying them to the resource. In a way, that was fitting since it was unclear which items are supposed to come first or whether order matters. It was updated to be more deterministic, since at least one rule has been inferred from above comments (“DOI should come last”). This should address the original ticket description.

- While I still believe that any XML diffing mechanism relying on inputs to be appropriately canonicalized is making a mistake (it should apply own normalization rules to all inputs, running c14n with a specific set of flags, re-formatting with consistent indentation, etc.—and ideally diff deserialized data structure, not strings; in test_paths.py I only diffed XML strings for the purposes of quick-and-dirty smoke testing), the XML should be canonicalized in the latest update.

- If we need returned XML to follow other conventions than canonicalization, that’d be another issue I suppose… From my understanding, that’d be an indication that XML is used as a presentation layer, which hinders either the evolution of the spec or user interoperability: a more extensive spec necessarily means either impaired human readability or stricter requirements to formatting (which most libraries for manipulating XML programmatically don’t tend to support, which may push some to resort to using the fragile approach of templating for building XML).
