### ISSUE TITLE
generated xml is not stable

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#241]
See https://mailarchive.ietf.org/arch/msg/tools-discuss/yRqq-psSVnB-qoNbICFvzZQDmIo.

While attributes and unordered-element order doesn't matter to XML parsers, it matters a lot to text differencing engines.

The output should be stable (repeated fetches should return identical bits, not seemingly randomly reordered ones).

**Comment by ronaldtse** [comment]
Transferred and acknowledged.

https://github.com/ietf-ribose/bibxml-service/issues/234 will address this issue.

**Comment by strogonoff** [comment]
We can canonicalize returned XML, but I’d like to learn more about the new use case being described.

For example, if there is XML diffing being done, isn’t it the responsibility of the differ to ensure all sources being diffed are canonicalized using the same method, rather than relying on API returning canonicalized XML and hoping it’s canonicalized with the same set of options?

**Comment by ronaldtse** [comment]
Thanks! Can we have a sample to see how the canonicalized content looks?

> While attributes and unordered-element order doesn't matter to XML parsers, it matters a lot to text differencing engines.

Text differencing engines should really not be relied upon for structured data content, but I recognise that in certain conditions, e.g. git, it is unavoidable.

**Comment by strogonoff** [comment]
> Text differencing engines should really not be relied upon for structured data content, but I recognise that in certain conditions, e.g. git, it is unavoidable.

Well, currently our diffs with xml2rfc are very large since we pretty-print XML while xml2rfc tools outputs un-indented lines. Canonicalization ignores indentation, so every indented line is a difference.

It’s just another illustration that a diffing layer shouldn’t trust service to return a normal form and do extra mangling, _going beyond the c14n spec,_ on its own to ensure both representations are truly as equivalent as possible.

**Comment by ronaldtse** [comment]
> It’s just another illustration that a diffing layer shouldn’t trust service to return a normal form and do extra mangling

I agree. A comparison can only work if the canonicalisation is run on both comparands.

**Comment by strogonoff** [comment]
> > It’s just another illustration that a diffing layer shouldn’t trust service to return a normal form and do extra mangling
> 
> I agree. A comparison can only work if the canonicalisation is run on both comparands.

Yes, it can ensure it runs the same canonicalization algorithm with the same parameters, and do any extra normalization beyond XML c14n spec if required.

**Comment by strogonoff** [comment]
The service canonicalizes XML now, and the order of elements should be consistent (more details: https://github.com/ietf-ribose/bibxml-service/issues/239#issuecomment-1193069048)
