### ISSUE TITLE
DOI fetch broken on demo site

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#32]
1. Go here https://demo.bibxml.org/doi/
2. Enter a valid DOI identifier, e.g. `10.6028/NIST.IR.7057` (this is a valid link: http://doi.org/10.6028/NIST.IR.7057)
3.
<img width="446" alt="Screenshot 2021-12-07 at 12 03 49 PM" src="https://user-images.githubusercontent.com/11865/144964203-695973c8-d00c-4369-8c59-d045e0bea4d0.png">

See it being redirected to `https://demo.bibxml.org/doi/10.6028%252FNIST.IR.7057/` and a failure message:
```
Requested reference not found: 10.6028/NIST.IR.7057
```

**Comment by strogonoff** [comment]
- This may be a regression, as it was previously tested against the previous demo IP per https://github.com/ietf-ribose/bibxml-service/issues/20#issuecomment-974278798. However, DOI logic did not fetch since that time.

- Alternatively, our new demo server infrastructure may fall within a DOI-blacklisted IP range. In that case it’s not an application-level bug but an infrastructure concern.

  I know that DOI blacklists IP ranges, because I was never able to get it to return anything besides 503 from my work machine, while the same cURL command worked fine on the old demo instance.

  For now I cannot try cURLing your reference from within demo infrastructure (no longer have SSH access), and because BibXML service misreports DOI’s 503 as 404 there’s no way of knowing. Once #34 is fixed, we’ll be able to identify whether DOI fetch regressed.

**Comment by ronaldtse** [comment]
> I know that DOI blacklists IP ranges, because I was never able to get it to return anything besides 503 from my work machine, while the same cURL command worked fine on the old demo instance.

Interesting find!

@kwkwan can you do some investigation in this area and provide support to @strogonoff in accessing the infrastructure? Thanks.

**Comment by strogonoff** [comment]
If that’s possible it’d be useful, but let’s not redeploy or push changes to bibxml-service today—I have many changes queued, including some post-refactor regression fixes and some improvements, so I’d rather avoid merge conflicts.

Also, I hope SSH access will not be necessary in the end after the fix to `bibxml-service` (and possibly `doi2ietf`) is ready and we see HTTP 503’s from DOI properly.

**Comment by strogonoff** [comment]
Crossref changed their API. Their new API docs provide some details on etiquette and how to avoid running into throttling, which is nice.

**Comment by ronaldtse** [comment]
> Also, while SSH access is convenient for testing access with cURL, I hope it will not be necessary in the end after the fix to bibxml-service (and possibly doi2ietf) is ready and we see HTTP 503’s from DOI properly.

@kwkwan is currently testing a new deployment that uses AWS resources and supports continuous deployment, will ping you when ready.

**Comment by strogonoff** [comment]
This is nearly fixed. Crossref integration is for the time being handled within BibXML service (which uses `crossrefapi` and converts most of the response into consistent internal format in https://github.com/ietf-ribose/bibxml-service/blob/main/sources/doi/__init__.py). Can later be ported to `doi2ietf-py`.

**Comment by strogonoff** [comment]
For the record, DOI fetch works now (try https://dev.bibxml.org/external-sources/doi/).

To add to my previous comment on implementation details, currently we cache results to reduce the number of requests to Crossref, so a change in DOI may not be reflected. Caching TTL may be moved to configuration, and/or we can allow user to re-retrieve while ignoring cache.
