### ISSUE TITLE
Unable to find "C57-12-20.2011" unless given "IEEE C57-12-20.2011"

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#48]
If I select the "IEEE" dataset, then enter "IEEE C57-12-20.2011", it works:
<img width="813" alt="Screenshot 2021-12-25 at 5 10 11 PM" src="https://user-images.githubusercontent.com/11865/147381832-69891bea-8497-47dd-a33c-c701dcc53194.png">

But if I enter "C57-12-20.2011", nothing is found:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/11865/147381815-f7e351f2-5e99-4faf-b1e9-1ee57725e951.png">

Having to require entering the dataset prefix ("IEEE") and then the document identifier with also the prefix "IEEE" seems redundant.

This seems to be an issue with the search engine matching strings.

**Comment by ronaldtse** [comment]
As previously discussed, requiring the user to enter the dataset is probably counter productive. We only need the user to distinguish whether they want to search for either:
1. An existing data item offered by the BibXML service (i.e. an indexed item)
2. An external ID (as in the DOI) that the BibXML service has no data on

**Comment by strogonoff** [comment]
@ronaldtse

For that citation, document type is “IEEE”, and document identifier is “IEEE C57-12-20.2011”. I personally think it’s redundant, but such is the canonical identifier we have.

Where would you get the incomplete identifier “C57-12-20.2011”? If some system provides such identifiers, perhaps this is a sign that we should adjust our canonical identifiers to make them less redundant?[0]

Otherwise, if we want fuzzy match behavior, this can be addressed in another issue. I think we should have a proper search widget for that, rather than giving extra magic behavior to the existing exact match widget, but will see…

[0] In case we have control over canonical identifiers, we could get rid of the duplication as filed in https://github.com/ietf-ribose/relaton-data-ieee/issues/5

**Comment by strogonoff** [comment]
> We only need the user to distinguish whether they want to search for either:

Search feature isn’t provided by the widget in the subject of this ticket. Only exact match by document type and ID.

If we to speak of fuzzy search experience, we shouldn’t require the user to select a document type in the first place, because the chance of identifier collision doesn‘t matter if you search.

There’s another widget that tries to provide this type of search functionality further below on the landing page. It should be improved and extended, though. Search-related ideas probably concern that widget.

**Comment by ronaldtse** [comment]
Yes, this canonical identifier is correct so we don't need to change it. I was more concerned about search as you pointed out. 

There are two issues from my question:
1. Specifying the "dataset" is sort of redundant because the document identifiers across all datasets are largely unique (one docID in one dataset is probably nonexistent in another). Eg. If the user selected "IEEE", specifying a docID with the prefix "IEEE" seems like a user experience that can be improved.
2. Users often enter slightly erroneous IDs and keywords, so fuzzy search is necessary. 

As you mentioned, let's move the discussion to the fuzzy search functionality.

**Comment by ronaldtse** [comment]
And another question: if we have good enough search, we don't need the exact match widget. Right?

**Comment by strogonoff** [comment]
Yes, so we seem to agree.

Exact match GUI is a good way to test the corresponding API endpoint so we might  keep it.

**Comment by strogonoff** [comment]
BibXML GUI has switched to a mixed-purpose widget, and while `C57-12-20.2011` does not yield an exact match it now redirects to search that shows the correct item.

We may further tweak this logic by checking if search yields a single bibitem and redirecting to that item in that case.
