### ISSUE TITLE
Implement BibXML dynamic anchors (required for legacy paths)

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#57]
Historically, the BibXML service had a matching file/URL path name to the `reference[@anchor]` attribute in the BibXML content.

This behavior is necessary for tools that assume the `anchor` to be identical to the file path:
* it is required for BibXML legacy paths
* may be (still) expected by authoring tools that utilize the BibXML Service for "directly incorporating" BibXML XML into their xml2rfc document 
  * which shouldn't be the case, but let's not break them now.

From @strogonoff:

> If we return new data from other sources for xml2rfc paths, then XML anchors will not match old xml2rfc anchors (presumably, the anchors in new data will contain some authoritative/canonical identifier, while the anchors in xml2rfc files match filenames that were arbitrarily assigned by humans).
>
> [...] we have to substitute anchors in XML based on whatever filename was in the incoming request (in case of legacy request, it would not match our anchor), on the fly.

From @TonyLHansen:
> I think “find, parse, construct and return” might be required.

_Originally posted by @strogonoff in https://github.com/ietf-ribose/bibxml-service/issues/18#issuecomment-990247132_

**Comment by strogonoff** [comment]
@ronaldtse so what would the “anchor”/filename be if the request is coming to something like http://dev.bibxml.org/api/v1/docid/ietf/IETF%20BCP%205?format=bibxml, for example?

**Comment by strogonoff** [comment]
The concept looks meaningless in context of file-less Web API interactions, so we have to get to the bottom of what effect does the anchor actually have on API consumers before acting on this.

**Comment by ronaldtse** [comment]
> @ronaldtse so what would the “anchor”/filename be if the request is coming to something like http://dev.bibxml.org/api/v1/docid/ietf/IETF%20BCP%205?format=bibxml, for example?

This functionality is ONLY for legacy URL paths.

Legacy clients will only use patterns like:
http://xml2rfc.tools.ietf.org/public/rfc/bibxml2/reference.W3C.CR-rdf-schema.xml

Where the `reference[@anchor]` is `W3C.CR-rdf-schema`.

**Comment by strogonoff** [comment]
@ronaldtse 

This document has anchor that does not match the requested filename: http://xml2rfc.tools.ietf.org/public/rfc/bibxml9/reference.BCP.0021.xml

What is the exact method of generating the `anchor` used by this document?

**Comment by strogonoff** [comment]
There is new algorithm of retrieving bibitems by xml2rfc-style path, which is by fuzzy matching: https://github.com/ietf-ribose/bibxml-service/blob/784c710d23836df448d05be8da084b6d3d98ce23/main/api_compat.py#L68-L78

This algorithm also sets anchor based on given legacy reference (filename).

Example:

https://dev.bibxml.org/public/rfc/bibxml2/reference.W3C.CR-rdf-schema.xml

**Comment by ronaldtse** [comment]
Thank you @strogonoff , this is exactly what we need for supporting legacy paths. The example path of https://dev.bibxml.org/public/rfc/bibxml2/reference.W3C.CR-rdf-schema.xml still provides incomplete data:

Original:
```xml
<reference anchor="W3C.CR-rdf-schema" target="http://www.w3.org/TR/2000/CR-rdf-schema-20000327">
  <front>
    <title>
Resource Description Framework (RDF) Schema Specification 1.0
</title>
    <author initials="D." surname="Brickley" fullname="Dan Brickley">
      <organization>University of Bristol</organization>
    </author>
    <author initials="R.V." surname="Guha" fullname="R.V. Guha">
      <organization>Epinions</organization>
    </author>
    <date day="27" month="March" year="2000"/>
  </front>
  <seriesInfo name="W3C" value="CR-rdf-schema"/>
</reference>
```

New:
```xml
<reference anchor="reference.W3C.CR-rdf-schema">
  <front>
    <title>
Resource Description Framework (RDF) Schema Specification 1.0
</title>
    <author fullname="Dan Brickley" surname="Brickley" initials="D">
      <organization>University of Bristol</organization>
    </author>
    <author fullname="R.V. Guha" surname="Guha" initials="R V">
      <organization>Epinions</organization>
    </author>
    <date year="2000" month="March" day="27"/>
  </front>
</reference>
```

But it's very close (old vs new):
* `anchor="W3C.CR-rdf-schema"` vs `anchor="reference.W3C.CR-rdf-schema"`
* `target="http://www.w3.org/TR/2000/CR-rdf-schema-20000327"` missing in new
* `<author initials="D." ...` vs `<author initials="D" ...`
* `<seriesInfo name="W3C" value="CR-rdf-schema"/>` missing in new

**Comment by strogonoff** [comment]
> anchor="W3C.CR-rdf-schema"

So we need to omit the `reference.` part?

> target="http://www.w3.org/TR/2000/CR-rdf-schema-20000327"

What is the algorithm for obtaining that, using data from a Relaton bibliographic item?

> <author initials="D." ... vs <author initials="D" ...

RFC 7991 recommends no trailing full stops, so I am processing them out from our data sources. We should really omit them in our sources in the first place.

> <seriesInfo name="W3C" value="CR-rdf-schema"/> missing in new

This is caused by the fact that we have a W3C document in misc which uses type “IETF” (https://github.com/ietf-ribose/relaton-data-misc/issues/2). The logic in new legacy path retrieval has `seriesInfo` extractor for `W3C`, but it relies on `docid` of type “W3C” to create a `seriesInfo` It gets `type=IETF`, so it tries to create an “Internet-Draft” or “RFC” `seriesInfo`, but document ID does not provide a suitable pattern, so it does not get any series info.

**Comment by strogonoff** [comment]
Implemented some of the measures, updated output:

https://dev.bibxml.org/public/rfc/bibxml2/reference.W3C.CR-rdf-schema.xml

For another example, here is an Internet Draft: https://dev.bibxml.org/public/rfc/bibxml3/reference.I-D.draft-wbeebee-6man-nd-proxy-std-00.xml

**Comment by strogonoff** [comment]
> @ronaldtse
> 
> This document has anchor that does not match the requested filename: http://xml2rfc.tools.ietf.org/public/rfc/bibxml9/reference.BCP.0021.xml
> 
> What is the exact method of generating the `anchor` used by this document?

@ronaldtse this question still stands.

Another example of a document where anchor does not match filename:

http://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcs/reference.RFC.8126.xml

Is it as simple as omitting the dot in given filename? Or should the anchor be obtained from some bibliographic item attribute?

**Comment by TonyLHansen** [comment]
the anchor is used in a couple different ways to generate the text of the RFCs. In particular, the anchor is what is published within the text between [], and at the end in the list of references it is the text printed on the left side of each reference. For example, "[RFC2822]" would show up in the text when using a <reference> with an anchor="RFC2822".

For RFCs and internet drafts, this text has been frozen based on what was generated by bibxml, and if someone wanted to use a DIFFERENT anchor, they would have to copy that <reference> XML into their doc and change the anchor manually.

But others of the bibxml libraries have supported a "?anchor='xyz'" option that would let you change, on the fly, the anchor text value that is returned to you. So instead of returning <reference anchor="RFC2822".../>, you could change it to read <reference anchor="EMAIL".../> and your document would print [EMAIL] everywhere.

There has been a long-expressed desire to extend this anchor=xyz to all of the bibxml libraries.

BTW, generating an anchor that looks like "reference.W3C.CR-rdf-schema" should be a non-starter. The long reference string of [W3C.CR-rdf-schema] has been acceptable to the community, but I think adding in "reference." to the string would not fly.

If there are specific mismatches in the current database between the returned anchors and the URL filenames, those are bugs, EXCEPT in the case where the anchor string contains characters such as "/".

**Comment by strogonoff** [comment]
> But others of the bibxml libraries have supported a "?anchor='xyz'" option that would let you change, on the fly, the anchor text value that is returned to you. So instead of returning <reference anchor="RFC2822".../>, you could change it to read <reference anchor="EMAIL".../> and your document would print [EMAIL] everywhere.
> 
> There has been a long-expressed desire to extend this anchor=xyz to all of the bibxml libraries.

I had a feeling this would be useful, so we do support `anchor` in primary API (e.g., https://dev.bibxml.org/api/v1/by-docid/?docid=NBS%20TN%201294&format=bibxml&anchor=something)

> BTW, generating an anchor that looks like "reference.W3C.CR-rdf-schema" should be a non-starter. The long reference string of [W3C.CR-rdf-schema] has been acceptable to the community, but I think adding in "reference." to the string would not fly.

Yes, now conforming to this behavior in xml2rfc compatibility API.

> If there are specific mismatches in the current database between the returned anchors and the URL filenames, those are bugs, EXCEPT in the case where the anchor string contains characters such as "/".

Got it. Haven‘t noticed such characters yet.

**Comment by strogonoff** [comment]
Implemented for items we generate XML for, but not yet for existing xml2rfc data.

**Comment by strogonoff** [comment]
Dynamic anchor is replaced in exiting xml2rfc data, when it’s used for fallback. It doesn’t attempt to parse XML, just uses a regular expression substitution. Does not add anchor if it’s missing.
