### ISSUE TITLE
Implement support for multiple API keys/tokens for use in API/GUI authentication

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#68]
From @kesara :

> Regarding administrative API keys,
> Implement those on the bibxml server side.
> We will only require a handful of those API keys for operations.
> There should be a straightforward way to add, remove administrative API keys.
> I guess even defining them on a configuration file will be sufficient.

We need to implement support for authenticating the `http://dev.bibxml.org/management/` endpoint using config-file determined administrative API keys.

**Comment by strogonoff** [comment]
This key is specified in environment. Operations can choose to either place `API_KEY="some_string"` in `.env` config file (see https://github.com/ietf-ribose/bibxml-service/blob/main/docs/howto/develop-locally.rst, just remember to never check it into VCS) or have it available in shell environment which runs the Docker Compose command.

**Comment by ronaldtse** [comment]
> Currently, operations can choose between placing API_KEY="some_string" in .env config file (see https://github.com/ietf-ribose/bibxml-service/blob/main/docs/howto/develop-locally.rst, just remember to never check it into VCS)

I believe we have to support multiple Administrative API keys. Do we support that already?

**Comment by strogonoff** [comment]
What is the use case for multiple administrative keys, compared to distributing and rotating a single key? We don’t track how different admin credentials are used.

**Comment by strogonoff** [comment]
Key revocation perhaps? I can see how multiple API keys can be useful in that scenario.

**Comment by ronaldtse** [comment]
> What is the use case for multiple administrative keys, compared to distributing and rotating a single key? We don’t track how different admin credentials are used.

There are multiple admins, and the ability to revoke will be useful if a key gets compromised (if known).

Key rotation can be implemented by actually changing the keys in the config + redeploy.

**Comment by strogonoff** [comment]
> Key rotation can be implemented by actually changing the keys in the config + redeploy.

Yes, that would be the approach.

We don’t offer API/GUI for managing keys. There’s a chicken and egg problem (there needs to be a master key anyway). This could be solved by adding an additional auth layer rather than supporting multiple keys (implement key management in the existing management GUI, which would remain accessible via singular `API_KEY`), but it seems unnecessarily complex compared to supporting multiple keys in master configuration.

If there is ever an actual use case for complex auth logic, we could (should?) revert to single master key, which would only be used for managing regular API keys used for routine operations.

**Comment by strogonoff** [comment]
Retitled the ticket according to clarifications.

**Comment by strogonoff** [comment]
Implemented and deployed. Environment variable `EXTRA_API_SECRETS` can contain comma-separated keys, each having the same effect as `API_KEY`.
