### ISSUE TITLE
Front page should just be a static page

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#75]
The front page is provides pretty much static information and we should not need to load anything from the database?

This would solve problems like this:
* The functionality that shows a "sample" of references occasionally runs into issues like this, which becomes rather unhelpful to the user.
<img width="469" alt="image" src="https://user-images.githubusercontent.com/11865/149040045-501ddcc9-42d9-4de1-a910-3474de636d4c.png">

**Comment by ronaldtse** [comment]
For some reason, the front page loads a lot slower than the indexed pages:

```console
$ time bash -c 'curl https://dev.bibxml.org > /dev/null' 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5845  100  5845    0     0    998      0  0:00:05  0:00:05 --:--:--  1529

real	0m5.869s
user	0m0.023s
sys	0m0.016s
$ time bash -c 'curl https://dev.bibxml.org/indexed-sources/rfcs/ > /dev/null' 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30909  100 30909    0     0  20860      0  0:00:01  0:00:01 --:--:-- 20955

real	0m1.498s
user	0m0.020s
sys	0m0.015s
```

It is probably loading too much data. There's no need to load data on this page?

**Comment by strogonoff** [comment]
@ronaldtse

- The request to retrieve doctypes ran on each page load, and involved a JSON query against PostgreSQL.
- It turns out that PostgreSQL, under memory and compute constraints (and without a tested indexing strategy), is not as fast to query data stored in a way that’s not pre-optimized for search.
- This single query routinely took between 1 and 2 seconds on my own dev setup (using Docker Compose on a cheap EC2 instance), and on our demo infrastructure it looks like it were taking much longer for some reason.

Measures taken:

- 1-day caching was enabled for the entire pre-rendered landing page. With a cache hit, loading is instant, the page is served essentially static (retrieved from cache, currently Redis, local memory cache was also tested).
- I believe with a new mixed-purpose search field there’s no need for doctype samples, so they were eliminated anyway. (If needed, we can provide curated/cached sample IDs later.)
- Notably, eliminating the query without enabling caching does not lead to instant page load, presumably server-side rendering causes latency.
