### ISSUE TITLE
Remove keywords from the bibxml

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#88]
Compare
https://dev.bibxml.org/api/v1/ref/rfcs/RFC8126/?format=bibxml
and
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcs/reference.RFC.8126.xml

Note that keywords do not appear in what we currently provide for RFC bibxml.

This service should also not provide keywords in RFC bibxml initially. We may choose to add them to the bibxml in the future, but the initial deployment should match what is currently available.

**Comment by ronaldtse** [comment]
Thanks @rjsparks , we will follow up with this.

Now there is one additional question. In the new output, we also have the `<workgroup>` element populated with the source data:

```xml
<workgroup>NON WORKING GROUP</workgroup>
```

Do we want to omit this as well, or keep it?

**Comment by strogonoff** [comment]
@rjsparks, note that the API endpoint for retrieving bibliographic data has changed (see https://github.com/ietf-ribose/bibxml-service/issues/6#issuecomment-1024914111).

Which means, instead of https://dev.bibxml.org/api/v1/ref/rfcs/RFC8126/?format=bibxml you’d use https://dev.bibxml.org/api/v1/by-docid/?docid=RFC8126&format=bibxml. The resulting XML would be the same as you’d get from https://dev.bibxml.org/public/rfc/bibxml/reference.RFC.8126.xml (apart from the anchor).

**Comment by strogonoff** [comment]
The source of this issue (as well as #86 and #85) is that the abovementioned superseded /ref/ endpoint still uses pre-generated xml data provided in `ietf-ribose/bibxml-data-*` repositories. The new endpoint generates XML on the fly, with following benefits:

- It already adheres to RFC 7991 a bit better.
- If issues are discovered, we don’t need to wait for bibxml sources to be updated and reindexed anymore.
- It also allows us to provide XML from external and semi-external sources (such as DOI and Datatracker), even if the data they return is in another format (we parse it into Relaton’s bibliographic item instance first, and then pass through `to_xml`).

**Comment by rjsparks** [comment]
> Now there is one additional question. In the new output, we also have the `<workgroup>` element populated with the source data:
> 
> ```
> <workgroup>NON WORKING GROUP</workgroup>
> ```
> 
> Do we want to omit this as well, or keep it?

That should be omitted.

**Comment by rjsparks** [comment]
> It already adheres to RFC 7991 a bit better.

Making use of something RFC7991 _allows_ is not the same as better adherence.

The Style Guide is what to adhere to here - it is a flaw if this system makes references that the RFC Editor then has to change before publishing an RFC.

> If issues are discovered, we don’t need to wait for bibxml sources to be updated and reindexed anymore.

Yet there will be issues that _have_ to rely on the bibxml sources. For instance, these keywords are not currently a well groomed set of data. The RPC and/or the community may decide at some point in the future to revise them.

(And in the datatracker, we have a slow but steady flow of corrections to author extractions of past drafts.

> The new endpoint generates XML on the fly

So it will have to carry the logic to implement these constraints.

**Comment by strogonoff** [comment]
Hmm. I see that RFC 7991 actually suggests `seriesInfo` inside `front`, and also does allow keywords. In that sense, as you can see, the new XML generation actually does not follow 7991 and follows more of what existing XML used to be provided by xml2rfc webserver.

**Comment by strogonoff** [comment]
> Yet there will be issues that have to rely on the bibxml sources. For instance, these keywords are not currently a well groomed set of data. The RPC and/or the community may decide at some point in the future to revise them.

Ideally, as far as I believe (@ronaldtse can correct me), the intent is to capture as much information as possible in Relaton data sources, and format subset of that data in XML according to RFC 7991 and/or xml2rfc needs.

So with the old approach, after source data is revised, both relaton-data sources and bibxml-data sources would need to be updated, but with the new implementation only relaton-data sources would need to be updated and new keywords, etc. will carry over to generated XML. And issues that do not concern source data but rather just XML serialization (such as where to put the `<seriesInfo>` node, which nodes to omit, etc.) can be done by changing `to_xml` logic without having to rebuild sources at all.

**Comment by ronaldtse** [comment]
@strogonoff the new approach is definitely the “correct” approach since it allows for easier changes in the future. 

With regards to RFC 7991, as indicated by @rjsparks , while supposed to be “current”, is in fact an outdated specification. The real RFC XML specification that is used/accepted now is more of a “spec by implantation” of the xml2rfc tool, which means that the goal posts are somewhat liquid. There is a history with RFC 7991 conflicting between synchronization of needs, wishes, and implementation. 

The best course of action (for us) is to tailor the BibXML to work with xml2rfc, then let that result propagate and fix up the successor of RFC 7991.

**Comment by ronaldtse** [comment]
This is all done. Closing.
